version: "3"

networks:
  gitlabkpis:

services:
  gitlabkpis:
    image: gitlabkpis-0.2
    ports:
      - "80:80"
    command: /start-reload.sh
    volumes:
      - ./app/main.py:/app/main.py
      - ./app/retro.py:/app/retro.py

    environment:
      - GL_ACCESS_TOKEN=${GL_ACCESS_TOKEN}
      - GL_SECRET=${GL_SECRET}
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - gitlabkpis
